### ISSUE TITLE
Compatibilility issue with Bourbon 5

### ISSUE THREAD

**Issue by openbrian** [Martskin/batch#12]
The align-items mixin has been removed.

**Comment by openbrian** [comment]
https://github.com/thoughtbot/bourbon/compare/da4451e...v5.0.0.beta.1

**Comment by openbrian** [comment]
https://github.com/thoughtbot/bourbon/compare/v4.2.6...v5.0.0.alpha.0

Specifically
https://github.com/thoughtbot/bourbon/commit/e5bb05c8c0613681684c60b39a642637f302a94b

**Comment by openbrian** [comment]
https://github.com/thoughtbot/bourbon/compare/v4.2.6...v5.0.0.alpha.0

Specifically
https://github.com/thoughtbot/bourbon/commit/dd3fdc8695da06688bbf90eaa3b905d6245df42b

**Comment by openbrian** [comment]
As a workaround you can just import '_flex-box';

https://github.com/thoughtbot/bourbon/blob/e5bb05c8c0613681684c60b39a642637f302a94b/app/assets/stylesheets/css3/_flex-box.scss

**Comment by Martskin** [comment]
Release 2.0.0 removes the Bourbon dependency.
